name = "BorrowChecker"
uuid = "7bdcaa52-c310-4bb0-bf54-d941056ed284"
version = "0.4.3"
authors = ["MilesCranmer <miles.cranmer@gmail.com>"]

[deps]
DispatchDoctor = "8d63f2c5-f18a-4cf2-ba9d-b3f60fc568c8"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
DispatchDoctor = "0.4.19"
MacroTools = "0.5"
Preferences = "1.4"
Random = "1"
julia = "1.10"
